apiVersion: v1
kind: ConfigMap
metadata:
  name: solfa-back
  namespace: solfa-space
data:
  DB_HOST: "147.79.114.72"
  DB_USER: "admin"
  DB_PASSWORD: "admin@2025"
  DB_NAME: "solfa"
  DB_PORT: 31432
  ES_HOST: "https://147.79.114.72:32000"
  ES_USER: "elastic"
  ES_PASSWORD: "c96bZD90kO31pG3YxX5VY24a"
