name: solfa-back-ci-dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification des secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME est vide ou non défini"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD est vide ou non défini"
            exit 1
          fi
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "PAT_TOKEN est vide ou non défini"
            exit 1
          fi

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/solfa:dev-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/solfa:dev-${{ github.sha }}

  modifygit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the manifests repository
        uses: actions/checkout@v4
        with:
          repository: 'aspitek/manifests'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copier le ConfigMap depuis le repo du code
        run: |
          # Télécharger le fichier ConfigMap depuis le repo du code
          curl -o solfa-back/configmap.yaml https://raw.githubusercontent.com/aspitek/solfa-back/main/k8s/configmap.yaml

      - name: Modifier l'image dans manifest.yml
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Modifier le tag d'image
          sed -i "s+image: .*$+image: ${{ secrets.DOCKER_USERNAME }}/solfa:dev-${{ github.sha }}+g" solfa-back/manifest.yml

          # Ajouter le fichier ConfigMap
          git add solfa-back/configmap.yaml

          # Commit des changements
          git add solfa-back/manifest.yml
          git commit -m "Mise à jour de l'image et du ConfigMap par GitHub Actions: Job changemanifest: ${{ github.run_number }}"

          git push origin main
